# Este arquivo define como será criado o cluster kubernetes
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4 # Define qual api que o kind irá utilizar para criar o cluster
name: k8s-studies # Nome do cluster

# A propriedade `nodes` define como e quantos nós (Nodes) serão criados no cluster
nodes:
# A propriedade role define qual será o papel/função do nó (Node)
- role: control-plane # Estou criando esse nó (Node) com a função/papel de gerenciar o cluster kubernetes (Kubernetes master/Node master)
- role: worker # Estou criando esse nó (Node) com a função/papel de ser um trabalhador (Common Node)
- role: worker # Estou criando esse nó (Node) com a função/papel de ser um trabalhador (Common Node)
- role: worker # Estou criando esse nó (Node) com a função/papel de ser um trabalhador (Common Node)